export const ACCENT_REGISTRY = {
  gold: {
    id: 'gold' as const,
    name: 'Gold',
    emoji: '🥇',
    primary: '#D4940C',
    primaryMuted: 'rgba(212,148,12,0.14)',
    primaryPressed: '#F0C240',
    gradientLight: '#F0B020',
    gradientDark: '#D4940C',
  },
  emerald: {
    id: 'emerald' as const,
    name: 'Emerald',
    emoji: '💚',
    primary: '#2E7D32',
    primaryMuted: 'rgba(46,125,50,0.14)',
    primaryPressed: '#43A047',
    gradientLight: '#43A047',
    gradientDark: '#1B5E20',
  },
  sapphire: {
    id: 'sapphire' as const,
    name: 'Sapphire',
    emoji: '💎',
    primary: '#0277BD',
    primaryMuted: 'rgba(2,119,189,0.14)',
    primaryPressed: '#039BE5',
    gradientLight: '#039BE5',
    gradientDark: '#01579B',
  },
  amethyst: {
    id: 'amethyst' as const,
    name: 'Amethyst',
    emoji: '💜',
    primary: '#8E24AA',
    primaryMuted: 'rgba(142,36,170,0.14)',
    primaryPressed: '#AB47BC',
    gradientLight: '#AB47BC',
    gradientDark: '#6A1B9A',
  },
  ruby: {
    id: 'ruby' as const,
    name: 'Ruby',
    emoji: '❤️',
    primary: '#D32F2F',
    primaryMuted: 'rgba(211,47,47,0.14)',
    primaryPressed: '#E53935',
    gradientLight: '#E53935',
    gradientDark: '#C62828',
  },
  sakura: {
    id: 'sakura' as const,
    name: 'Sakura',
    emoji: '🌸',
    primary: '#E8749A',
    primaryMuted: 'rgba(232,116,154,0.14)',
    primaryPressed: '#F09AB8',
    gradientLight: '#F090B8',
    gradientDark: '#D4607E',
  },
  turquoise: {
    id: 'turquoise' as const,
    name: 'Turquoise',
    emoji: '💠',
    primary: '#00897B',
    primaryMuted: 'rgba(0,137,123,0.14)',
    primaryPressed: '#26A69A',
    gradientLight: '#26A69A',
    gradientDark: '#004D40',
  },
  silver: {
    id: 'silver' as const,
    name: 'Silver',
    emoji: '🥈',
    primary: '#90A4AE',
    primaryMuted: 'rgba(144,164,174,0.14)',
    primaryPressed: '#B0BEC5',
    gradientLight: '#B0BEC5',
    gradientDark: '#455A64',
  },
  indigo: {
    id: 'indigo' as const,
    name: 'Indigo',
    emoji: '🔷',
    primary: '#3949AB',
    primaryMuted: 'rgba(57,73,171,0.14)',
    primaryPressed: '#5C6BC0',
    gradientLight: '#5C6BC0',
    gradientDark: '#1A237E',
  },
  peridot: {
    id: 'peridot' as const,
    name: 'Peridot',
    emoji: '🫒',
    primary: '#9E9D24',
    primaryMuted: 'rgba(158,157,36,0.14)',
    primaryPressed: '#C0CA33',
    gradientLight: '#C0CA33',
    gradientDark: '#827717',
  },
} as const;

export type AccentId = keyof typeof ACCENT_REGISTRY;
export type AccentConfig = (typeof ACCENT_REGISTRY)[AccentId];

export const FREE_ACCENT_IDS: readonly AccentId[] = [
  'gold',
  'emerald',
  'sapphire',
  'amethyst',
  'ruby',
  'sakura',
  'turquoise',
  'silver',
  'indigo',
  'peridot',
];

export function isAccentFree(id: AccentId): boolean {
  return true;
}
